const CdnCardsBlockQuery = `
...  on ComponentPageBlocksCdnCards{
  contactContent
  tabFirstTitleCDN
  innerFirstTitle
  tabSecondTitleCDN
  innerSecondTitle
  firstCDNCard{
    titleCDN
    descriptionCDN
    performancesCDNCard
    saveTextCdnCard
    cdn_product{
      data{
        attributes{
          title
          sku
          productType
          productType
          description
          productCategory{
            data{
              attributes{
                sku
              }
            }
          }
          resourceVersion
          metadata
          productPrices{
            data{
              attributes{
                sku
                price
                currency
                period
                priceType
                pricingModel
                resourceVersion
                tiers
              }
            }
          }
        }
      }
    }
    cdn_addon{
      data{
        attributes{
          title
          sku
          productType
          productType
          description
          productCategory{
            data{
              attributes{
                sku
              }
            }
          }
          resourceVersion
          metadata
          productPrices{
            data{
              attributes{
                sku
                price
                currency
                period
                priceType
                pricingModel
                resourceVersion
                tiers
              }
            }
          }
        }
      }
    }
  }
  secondCDNCard{
    titleCDN
    descriptionCDN
    performancesCDNCard
    saveTextCdnCard
    cdn_product{
      data{
        attributes{
          title
          sku
          productType
          productType
          description
          productCategory{
            data{
              attributes{
                sku
              }
            }
          }
          resourceVersion
          metadata
          productPrices{
            data{
              attributes{
                sku
                price
                currency
                period
                priceType
                pricingModel
                resourceVersion
                tiers
              }
            }
          }
        }
      }
    }
    cdn_addon{
      data{
        attributes{
          title
          sku
          productType
          productType
          description
          productCategory{
            data{
              attributes{
                sku
              }
            }
          }
          resourceVersion
          metadata
          productPrices{
            data{
              attributes{
                sku
                price
                currency
                period
                priceType
                pricingModel
                resourceVersion
                tiers
              }
            }
          }
        }
      }
    }
  }
  thirdCDNCard{
    titleCDN
    descriptionCDN
    performancesCDNCard
    saveTextCdnCard
    cdn_product{
      data{
        attributes{
          title
          sku
          productType
          productType
          description
          productCategory{
            data{
              attributes{
                sku
              }
            }
          }
          resourceVersion
          metadata
          productPrices{
            data{
              attributes{
                sku
                price
                currency
                period
                priceType
                pricingModel
                resourceVersion
                tiers
              }
            }
          }
        }
      }
    }
    cdn_addon{
      data{
        attributes{
          title
          sku
          productType
          productType
          description
          productCategory{
            data{
              attributes{
                sku
              }
            }
          }
          resourceVersion
          metadata
          productPrices{
            data{
              attributes{
                sku
                price
                currency
                period
                priceType
                pricingModel
                resourceVersion
                tiers
              }
            }
          }
        }
      }
    }
  }
  firstCDNddosCard{
    titleCDN
    descriptionCDN
    performancesCDNCard
    saveTextCdnCard
    cdn_product{
      data{
        attributes{
          title
          sku
          productType
          productType
          description
          productCategory{
            data{
              attributes{
                sku
              }
            }
          }
          resourceVersion
          metadata
          productPrices{
            data{
              attributes{
                sku
                price
                currency
                period
                priceType
                pricingModel
                resourceVersion
                tiers
              }
            }
          }
        }
      }
    }
    cdn_addon{
      data{
        attributes{
          title
          sku
          productType
          productType
          description
          productCategory{
            data{
              attributes{
                sku
              }
            }
          }
          resourceVersion
          metadata
          productPrices{
            data{
              attributes{
                sku
                price
                currency
                period
                priceType
                pricingModel
                resourceVersion
                tiers
              }
            }
          }
        }
      }
    }
  }
  secondCDNddosCard{
    titleCDN
    descriptionCDN
    performancesCDNCard
    saveTextCdnCard
    cdn_product{
      data{
        attributes{
          title
          sku
          productType
          productType
          description
          productCategory{
            data{
              attributes{
                sku
              }
            }
          }
          resourceVersion
          metadata
          productPrices{
            data{
              attributes{
                sku
                price
                currency
                period
                priceType
                pricingModel
                resourceVersion
                tiers
              }
            }
          }
        }
      }
    }
    cdn_addon{
      data{
        attributes{
          title
          sku
          productType
          productType
          description
          productCategory{
            data{
              attributes{
                sku
              }
            }
          }
          resourceVersion
          metadata
          productPrices{
            data{
              attributes{
                sku
                price
                currency
                period
                priceType
                pricingModel
                resourceVersion
                tiers
              }
            }
          }
        }
      }
    }
  }
  thirdCDNddosCard{
    titleCDN
    descriptionCDN
    performancesCDNCard
    saveTextCdnCard
    cdn_product{
      data{
        attributes{
          title
          sku
          productType
          productType
          description
          productCategory{
            data{
              attributes{
                sku
              }
            }
          }
          resourceVersion
          metadata
          productPrices{
            data{
              attributes{
                sku
                price
                currency
                period
                priceType
                pricingModel
                resourceVersion
                tiers
              }
            }
          }
        }
      }
    }
    cdn_addon{
      data{
        attributes{
          title
          sku
          productType
          productType
          description
          productCategory{
            data{
              attributes{
                sku
              }
            }
          }
          resourceVersion
          metadata
          productPrices{
            data{
              attributes{
                sku
                price
                currency
                period
                priceType
                pricingModel
                resourceVersion
                tiers
              }
            }
          }
        }
      }
    }
  }
}
`;
export default CdnCardsBlockQuery;
